
import Footers from "./components/footer"
import Header from "./components/Header"


export const metadata = {
  title: 'Equity BCDC | Diaspora',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
       <Header/>
        {children}
        <Footers/>
        </body>
      
    </html>
  )
}
